# Generated by Django 3.1.1 on 2020-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=60, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('enable', models.CharField(default='1', max_length=1)),
                ('idx', models.IntegerField(default=99)),
            ],
        ),
    ]
