# Generated by Django 3.1.1 on 2020-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('eng_name', models.CharField(max_length=60, null=True)),
                ('url', models.CharField(max_length=60, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('enable', models.CharField(default='1', max_length=1)),
                ('idx', models.IntegerField(default=99)),
                ('data_feather', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
