# Generated by Django 3.1.1 on 2020-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_sitenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=30)),
                ('ltime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=60)),
            ],
        ),
    ]
